# Generated by Django 6.0.3 on 2026-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WywozSmieci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('typ_odpadu', models.CharField(choices=[('zmieszane', 'Zmieszane odpady komunalne'), ('opakowaniowe', 'Zmieszane odpady opakowaniowe'), ('papier', 'Papier'), ('biodegradowalne', 'Odpady biodegradowalne'), ('popiol', 'Popiół')], max_length=20)),
            ],
            options={
                'verbose_name': 'Wywóz śmieci',
                'verbose_name_plural': 'Wywozy śmieci',
                'ordering': ['data'],
            },
        ),
    ]
