# Generated by Django 6.0.3 on 2026-04-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonogram', '0002_alter_wywozsmieci_typ_odpadu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wywozsmieci',
            name='typ_odpadu',
            field=models.CharField(choices=[('zmieszane', 'Zmieszane'), ('opakowaniowe', 'Plastik'), ('papier', 'Papier'), ('szklo', 'Szkło'), ('biodegradowalne', 'Odpady biodegradowalne'), ('popiol', 'Popiół')], max_length=20),
        ),
    ]
